apis_ontology/urls.py
from apis_acdhch_default_settings.urls import urlpatterns
from django.urls import include, path

urlpatterns += [path("", include("mine_frontend.urls"))]
urlpatterns += [path("", include("apis_acdhch_django_invite.urls"))]
urlpatterns += [path("", include("django_interval.urls"))]
urlpatterns += [
    path("", include("apis_acdhch_django_auditlog.urls")),
]
urlpatterns += [
    path("", include("mine_edit.urls")),
]

mine_edit/urls.py
from django.urls import path

from mine_edit.views import (
    CareerCreateView,
    CareerEditView,
    EducationCreateView,
    EducationEditView,
    PersonEditView,
)

app_name = "mine_edit"
urlpatterns = [
    path(
        "education/<int:pk>/edit/", EducationEditView.as_view(), name="education_edit"
    ),
    path(
        "education/<int:pk_subj>/create/",
        EducationCreateView.as_view(),
        name="education_create",
    ),
    path("career/<int:pk>/edit/", CareerEditView.as_view(), name="career_edit"),
    path(
        "career/<int:pk_subj>/create/",
        CareerCreateView.as_view(),
        name="career_create",
    ),
    path(
        "member/<int:pk>/edit/",
        PersonEditView.as_view(),
        name="member_edit",
    ),
]

mine_frontend/urls.py
from django.urls import path
from django.views.generic import TemplateView

from mine_frontend.autocompletes import OEAWInstitutionsDal, VorschlagendeDal
from mine_frontend.views import (
    IndexView,
    InstitutionIndexView,
    InstitutionResultsView,
    OEAWInstitutionDetailView,
    OEAWMemberDetailView,
    OEAWPrizeDetailView,
    PersonResultsView,
)

app_name = "mine_frontend"

urlpatterns = [
    path("mine/", IndexView.as_view(), name="index"),
    path("mine-institution/", InstitutionIndexView.as_view(), name="institution-index"),
    path(
        "about/",
        TemplateView.as_view(template_name="mine_frontend/about.html"),
        name="about",
    ),
    path("person/<int:pk>/", OEAWMemberDetailView.as_view(), name="person-detail"),
    path(
        "institution/<int:pk>/",
        OEAWInstitutionDetailView.as_view(),
        name="institution-detail",
    ),
    path(
        "preis/<int:pk>/",
        OEAWPrizeDetailView.as_view(),
        name="prize-detail",
    ),
    path("search/", PersonResultsView.as_view(), name="search"),
    path(
        "search_institution/",
        InstitutionResultsView.as_view(),
        name="institution-search",
    ),
    path("ac/vorgeschlagende", VorschlagendeDal.as_view(), name="dal-vorschlagende"),
    path("ac/institute", OEAWInstitutionsDal.as_view(), name="dal-institute"),
]

mine_frontend/views.py
import datetime
import re

from apis_core.uris.models import Uri
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.postgres.expressions import ArraySubquery
from django.db.models import Case, F, IntegerField, OuterRef, Q, Subquery, Value, When
from django.db.models.functions import Concat, Lower
from django.views import generic
from django.views.generic.base import TemplateView
from django_tables2.views import SingleTableView

from apis_ontology.models import (
    AusbildungAn,
    AutorVon,
    Bild,
    EhrentitelVonInstitution,
    ErwaehntIn,
    GeborenIn,
    GestorbenIn,
    Gewinnt,
    HaeltRedeBei,
    Institution,
    InstitutionHierarchie,
    Mitglied,
    NichtGewaehlt,
    OeawMitgliedschaft,
    Person,
    PositionAn,
    Preis,
    Werk,
    WirdVergebenVon,
)
from mine_edit.utils import user_edit_permissions
from mine_frontend.forms import InstitutionMainForm, MineMainform
from mine_frontend.mixins import FacetedSearchMixin
from mine_frontend.settings import POSITIONEN_PRES
from mine_frontend.tables import SearchResultInstitutionTable, SearchResultTable


def get_web_object_uri(uri_obj):
    def get_identifier(uri_obj):
        if "geschichtewiki" in uri_obj.uri:
            return uri_obj.uri.split("=")[-1]
        elif "parlament" in uri_obj.uri:
            return re.search(r"PAD_(\d+)", uri_obj.uri).group(1)
        elif "deutsche-biographie" in uri_obj.uri:
            return re.search(r"/([0-9A-Z]+)\.html", uri_obj.uri).group(1)
        else:
            return uri_obj.uri.split("/")[-1]

    return {
        "uri": uri_obj.uri,
        "kind": uri_obj.short_label,
        "identifier": get_identifier(uri_obj),
    }


class OEAWMemberDetailView(LoginRequiredMixin, generic.DetailView):
    model = Person
    queryset = Person.objects.filter(mitglied=True)
    context_object_name = "oeaw_member"
    template_name = "mine_frontend/oeaw_member_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["has_edit_permissions"] = user_edit_permissions(
            self.request.user, self.object
        )
        membership_list = list(
            OeawMitgliedschaft.objects.filter(subj_object_id=self.object.id)
        ) + list(NichtGewaehlt.objects.filter(subj_object_id=self.object.id))
        context["membership"] = sorted(
            membership_list,
            key=lambda obj: getattr(obj, "beginn_date_sort", None)
            or getattr(obj, "datum_date_sort", None)
            or datetime.date.today(),
        )
        context["membership_short"] = (
            OeawMitgliedschaft.objects.filter(subj_object_id=self.object.id)
            .exclude(beginn_typ="gewählt, nicht bestätigt")
            .order_by("beginn_date_sort")
        )
        context["place_of_birth"] = GeborenIn.objects.filter(
            subj_object_id=self.object.id
        )
        context["place_of_death"] = GestorbenIn.objects.filter(
            subj_object_id=self.object.id
        )
        context["education"] = AusbildungAn.objects.filter(
            subj_object_id=self.object.id
        ).order_by(
            Case(When(typ="Schule", then=Value(0)), default=Value(1)),
            "beginn_date_sort",
        )
        context["honour_titles"] = EhrentitelVonInstitution.objects.filter(
            subj_object_id=self.object.id
        )
        inst_akad = Institution.objects.filter(pk=OuterRef("obj_object_id"))
        career = (
            PositionAn.objects.filter(subj_object_id=self.object.id)
            .annotate(
                _inst_akad=inst_akad.values("akademie_institution"),
                _inst_typ=inst_akad.values("typ"),
                _inst_name=Lower(inst_akad.values("label")),
                _sort_date=Case(
                    When(beginn_date_sort__isnull=False, then="beginn_date_sort"),
                    default="ende_date_sort",
                ),
            )
            .order_by("_sort_date")
        )
        context["career"] = career.exclude(_inst_akad=True)
        context["career_akad"] = {}

        pres = career.exclude(_inst_akad=False).filter(
            position="Präsident(in)",
            _inst_name__in=[
                "gesamtakademie",
                "junge akademie",
                "junge kurie",
                "mathematisch-naturwissenschaftliche klasse",
                "philosophisch-historische klasse",
            ],
        )
        viz_pres = career.exclude(_inst_akad=False).filter(
            position="Vizepräsident(in)",
            _inst_name__in=[
                "gesamtakademie",
                "junge akademie",
                "junge kurie",
                "mathematisch-naturwissenschaftliche klasse",
                "philosophisch-historische klasse",
            ],
        )
        sek = career.exclude(_inst_akad=False).filter(
            position="Sekretär(in)",
            _inst_name__in=[
                "gesamtakademie",
                "junge akademie",
                "junge kurie",
                "mathematisch-naturwissenschaftliche klasse",
                "philosophisch-historische klasse",
            ],
        )
        gen_sek = career.exclude(_inst_akad=False).filter(
            position="Generalsekretär(in)",
            _inst_name__in=[
                "gesamtakademie",
                "junge akademie",
                "junge kurie",
                "mathematisch-naturwissenschaftliche klasse",
                "philosophisch-historische klasse",
            ],
        )
        obm = career.exclude(_inst_akad=False).filter(
            position="Obmann/Obfrau (Kommission)"
        )
        kom_mitgl = career.exclude(_inst_akad=False).filter(
            position="Kommissionsmitglied"
        )
        pos_other_inst = (
            career.exclude(_inst_akad=False)
            .exclude(position="Sekretär(in)")
            .exclude(position="Präsident(in)")
            .exclude(position="Vizepräsident(in)")
            .exclude(position="Kommissionsmitglied")
            .exclude(position="Obmann/Obfrau (Kommission)")
            .exclude(position="Delegierte(r)")
            .exclude(position="Generalsekretär(in)")
        )
        proposed_success = OeawMitgliedschaft.objects.filter(
            vorgeschlagen_von=self.object.id
        ).order_by("beginn_date_sort")
        proposed_unsuccess = NichtGewaehlt.objects.filter(
            vorgeschlagen_von=self.object.id
        ).order_by("datum_date_sort")
        delegations = career.filter(_inst_typ="Delegation")

        if any(
            qs.exists()
            for qs in [
                pres,
                viz_pres,
                sek,
                gen_sek,
                obm,
                kom_mitgl,
                proposed_success,
                proposed_unsuccess,
                delegations,
                pos_other_inst,
            ]
        ):
            context["career_akad"] = {
                "pres": pres,
                "viz_pres": viz_pres,
                "sek": sek,
                "gen_sek": gen_sek,
                "obm": obm,
                "kom_mitgl": kom_mitgl,
                "pos_other_inst": pos_other_inst,
                "proposed_success": proposed_success,
                "proposed_unsuccess": proposed_unsuccess,
                "delegations": delegations,
            }
        else:
            context["career_akad"] = False
        IMG_ORDER = ["User", "OEAW Archiv", "Wikimedia"]
        img_order = Case(
            *[When(art=value, then=Value(pos)) for pos, value in enumerate(IMG_ORDER)],
            default=Value(len(IMG_ORDER)),
            output_field=IntegerField(),
        )
        context["image"] = (
            Bild.objects.filter(object_id=self.object.id)
            .annotate(order=img_order)
            .order_by("order")
            .first()
        )
        context["reference_resources"] = [
            get_web_object_uri(x) for x in Uri.objects.filter(object_id=self.object.id)
        ]
        context["prizes"] = Gewinnt.objects.filter(
            subj_object_id=self.object.id
        ).order_by("datum_date_sort")
        inst_member = Institution.objects.filter(pk=OuterRef("obj_object_id"))
        member = (
            Mitglied.objects.filter(subj_object_id=self.object.id)
            .annotate(
                _inst_kind=inst_member.values("typ"),
                _inst_label=inst_member.values("label"),
            )
            .order_by("beginn_date_sort")
        )
        context["memb_akad"] = member.filter(_inst_kind="Akademie (Ausland)")
        context["nazi"] = member.filter(_inst_label__icontains="nationalsozialistisch")
        nekrolog = Werk.objects.filter(pk=OuterRef("obj_object_id"))
        aut_nekro_pre = (
            AutorVon.objects.filter(subj_object_id=self.object.id)
            .annotate(_title=nekrolog.values("titel"))
            .values("obj_object_id")
            .filter(_title__icontains="nekrolog")
        )
        context["nekrologe_verfasst"] = ErwaehntIn.objects.filter(
            obj_object_id__in=aut_nekro_pre
        )
        own_nekro_pre = AutorVon.objects.filter(
            obj_object_id__in=ErwaehntIn.objects.filter(subj_object_id=self.object.id)
            .annotate(_title=nekrolog.values("titel"))
            .filter(_title__icontains="nekrolog")
            .values("obj_object_id")
        )
        if own_nekro_pre.exists():
            context["own_nekro"] = own_nekro_pre.first()
        context["speaches"] = HaeltRedeBei.objects.filter(subj_object_id=self.object.id)
        context["entity_type"] = "person"

        return context

    def get(self, *args, **kwargs):
        resp = super().get(*args, **kwargs)
        resp["HX-Trigger"] = "dismissModal"
        return resp


class OEAWInstitutionDetailView(LoginRequiredMixin, generic.DetailView):
    model = Institution

mine_frontend/templates/mine_frontend/about.html
{% extends "mine_frontend/base.html" %}
{% load static %}
{% block content %}
    <div class="wrapper" id="wrapper-hero">
        <!-- ******************* The Hero Area ******************* -->
        <div class="wrapper  pb-0" id="wrapper-hero-content">
            <div class="container pl-5 pr-5 hero-light"
                 id="wrapper-hero-inner"
                 tabindex="-1">
                <div class="row m-0 bg-mine border-mine p-1">
                    <h1 class="w-50  font-weight-bold">Über das Projekt</h1>
                </div>
            </div>
            <!-- #wrapper-hero-content -->
        </div>
        <div class="wrapper pt-0" id="index-wrapper">
            <div class="container pl-5 pr-5" id="content" tabindex="-1">
                <div class="row">
                    <div class="col-md-8 col-lg-6">
                        <p>
                            ÖAW M|I|N|E bereitet erstmals die Geschichte der Österreichischen
                            Akademie der
                            Wissenschaften, gegründet 1847, in digitaler Form auf. M|I|N|E steht für
                            Mitglieder |
                            Institutionen | Netzwerke | Ereignisse.
                        </p>
                        <p>
                            Die Datenbank erfasst alle gegenwärtigen und historischen Mitglieder der
                            Akademie (rund 3.000 Wissenschaftler:innen), ihre etwa 80 Institute, 365
                            Kommissionen und andere Forschungseinrichtungen. Darüber hinaus werden
                            zentrale Ereignisse wie z.B. die jährlichen Feierlichen Sitzungen,
                            Festreden, Preisausschreibungen u.a. dokumentiert. Die in M|I|N|E
                            aufbereiteten Daten wurden auf Grundlage von Beständen des ÖAW-Archivs
                            sowie von Akademieveröffentlichungen wissenschaftlich recherchiert.
                        </p>
                        <p>
                            Die erfassten Daten können sowohl in Form von Individualprofilen
                            angezeigt als auch in Verbindung mit Akademieinstitutionen und
                            Ereignissen ausgewertet und als Netzwerke visualisiert werden.
                        </p>
                        <p>
                            ÖAW M|I|N|E ist work in progress. Der Datenbestand umfasst derzeit
                            sämtliche Mitglieder der Akademie. Detaillierte biografische Angaben
                            liegen für Personen vor, die bis 1955 (kMI) bzw. bis 1970 (wM) zu
                            Mitgliedern gewählt wurden, sowie für die heutigen Mitglieder.
                            Korrespondierende Mitglieder im Ausland und Ehrenmitglieder sind derzeit
                            ausschließlich mit ihren Funktionen innerhalb der Akademie erfasst.
                        </p>
                        <!-- Your content here -->
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block scriptFooter %}
{% endblock scriptFooter %}

mine_frontend/templates/mine_frontend/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport"
              content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <meta name="htmx-config"
              content='{"responseHandling":[ {"code":"204", "swap": true}, {"code":"[23]..", "swap": true}, {"code":"[45]..", "swap": false, "error":true}, {"code":"...", "swap": false}]}' />
        <title>
            {% block title %}Geschichte der Akademie{% endblock %}
        </title>
        {% block scriptHeader %}
            {% load sass_tags %}
            <link rel="stylesheet"
                  href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.3.4/leaflet.css" />
            <link rel="stylesheet"
                  href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.5.3/MarkerCluster.css" />
            <link rel="stylesheet"
                  href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.5.3/MarkerCluster.Default.css" />
            <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600&display=swap"
                  rel="stylesheet">
            <link rel="preconnect" href="https://fonts.gstatic.com">
            <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,300;0,400;1,400&display=swap"
                  rel="stylesheet">
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
            <link rel="stylesheet" href="{% static 'lightbox/css/lightbox.min.css' %}" />
            <link href="{% sass_src 'mine_frontend/css/theme.scss' %}"
                  rel="stylesheet"
                  type="text/css" />
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
            <!-- Select2 CSS -->
            <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css"
                  rel="stylesheet" />
            <link href="https://cdn.jsdelivr.net/npm/select2-bootstrap-5-theme@1.3.0/dist/select2-bootstrap-5-theme.min.css"
                  rel="stylesheet" />
            <link href="{% static 'css/override_bootstrap.min.css' %}" rel="stylesheet" />
            <link href="{% static 'css/material-symbols.css' %}" rel="stylesheet" />
            <link href="{% static 'css/core.css' %}" rel="stylesheet" />
            <link href="{% static 'css/E53_Place_popover.css' %}" rel="stylesheet" />
            <!-- Select2 JS -->
            <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
            <script src="{% static 'bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
            <!-- Custom styles for this template -->
            <script src="{% static 'feather/feather.min.js' %}"></script>
            <!-- lightbox -->
            <script src="{% static 'lightbox/js/lightbox.min.js' %}"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/1.1.2/js/bootstrap-multiselect.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.3.4/leaflet.js"></script>
            <script src="https://unpkg.com/htmx.org@2.0.4" defer></script>
            <script src="{% static 'js/core.js' %}"></script>
            <script src="{% static 'js/E53_Place_popover.js' %}"></script>
            <script src="{% static 'js/apis_select2.js' %}"></script>
            <script src="{% static 'autocomplete_light/autocomplete_light.js' %}"></script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
                    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
                    crossorigin="anonymous"
                    defer></script>
        {% endblock %}
    </head>
    <body id="body" data-searchtype="erw" class="bg-mine">
        <div class="hfeed site bg-white" id="page">
            <!-- NAVBAR
================================================== -->
            <!-- ******************* The Navbar Area ******************* -->
            <div class="wrapper-fluid wrapper-navbar sticky-navbar"
                 id="wrapper-navbar"
                 itemscope
                 itemtype="http://schema.org/WebSite">
                <nav class="navbar navbar-expand-lg navbar-light">
                    <div class="container">
                        <a href="/"
                           class="navbar-brand custom-logo-link w-100 h-100"
                           rel="home"
                           itemprop="url"><!--<h3>PAAS</h3>-->
                            <img class="w-100 h-100"
                                 src="{% static 'mine_frontend/img/MINE_logo.svg' %}" />
                        </a><!-- end custom logo -->
                        <button class="navbar-toggler"
                                type="button"
                                data-bs-toggle="collapse"
                                data-bs-target="#navbarSupportedContent"
                                aria-controls="navbarSupportedContent"
                                aria-expanded="false"
                                aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse align-items-start justify-content-start"
                             id="navbarSupportedContent">
                            <!-- Your menu goes here -->
                            <ul id="main-menu"
                                class="navbar-nav me-0 fw-bold flex-column text-uppercase">
                                <li class="nav-item">
                                    <a title="Mitglieder"
                                       href="{% url 'mine_frontend:index' %}"
                                       class="nav-link p-0">Mitglieder</a>
                                </li>
                                <li class="nav-item">
                                    <a title="Institutionen"
                                       href="{% url 'mine_frontend:institution-index' %}"
                                       class="nav-link p-0">Institutionen</a>
                                </li>
                                <li class="nav-item nav-link p-0" style="color: grey">Netzwerke</li>
                                <li class="nav-item nav-link p-0" style="color: grey">Ereignisse</li>
                            </ul>
                            <form class="d-flex my-2 my-lg-0 pt-1 navbar-search-form"
                                  method="get"
                                  action=" {% if 'institution' in request.path %} /institutionen/search {% else %} /search {% endif %} "
                                  role="search">
                                <input class="form-control navbar-search rounded-0 border-0"
                                       id="s"
                                       name="q"
                                       type="text"
                                       placeholder=""
                                       value=""
                                       autocomplete="off">
                                <button type="submit" class="navbar-search-icon pt-1">
                                    <i data-feather="search"></i>
                                </button>
                            </form>
                            <ul id="second-menu"
                                class="navbar-nav me-0 align-top ps-lg-5 flex-column text-uppercase fw-light">
                                <li class="nav-item">
                                    <a title="Über"
                                       href="{% url 'mine_frontend:about' %}"
                                       class="nav-link p-0">Über</a>
                                </li>
                                <li class="nav-item">
                                    <a title="Kontakt" href="FIXME" class="nav-link p-0">Kontakt</a>
                                </li>
                                <li class="nav-item">
                                    <a title="Kontakt" href="FIXME" class="nav-link p-0">Stories</a>
                                </li>
                            </ul>
                        </div>
                        <!-- .collapse navbar-collapse -->
                    </div>
                    <!-- .container -->
                </nav>
                <!-- .site-navigation -->
            </div>
            <!-- .wrapper-navbar end -->
            <div class="h-100" id="content">
                {% block content %}{% endblock %}
            </div>
            <dialog id="relationdialog">
                <div id="relation-dialog-content"></div>
            </dialog>
            <div id="footer"
                 class="footer {% if 'institution' in request.path %} border-mine-institutions {% else %} border-mine {% endif %} mlr-30">
                <div class="container">
                    <footer>
                        <div class="row">
                            <div class="col-8 footermenu">
                                <ul class="nav list-inline justify-content-between">
                                    <li class="pb-1 ps-0 list-inline-item">
                                        <small><a title="Impressum" href="FIXME">Impressum</a></small>
                                    </li>
                                    <li class="pb-1 ps-0 list-inline-item">
                                        <small><a title="Impressum" href="FIXME">Datenschutz</a></small>
                                    </li>
                                    <li class=" ps-0 list-inline-item text-oeaw-blue">
                                        <small>&#xa9; Österreichische Akademie der Wissenschaften</small>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-4 text-end">
                                <i onclick="scrollToTop()" data-feather="arrow-up"></i>
                            </div>
                        </div>
                    </footer>
                </div>
            </div>
            <button type="button" class="btn btn-floating btn-lg" id="btn-back-to-top">
                <span>↑</span>
            </button>
        <!-- <script src="https://cdn.rawgit.com/afeld/bootstrap-toc/v1.0.1/dist/bootstrap-toc.min.js"></script>
                                                                                                                            <script type="text/javascript"
                                                                                                                                    src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script> -->
        <script>feather.replace()</script>
        <script>
    function scrollToTop() {
      $('body,html').animate({
        scrollTop : 0
    }, 500);
    };
    document.body.addEventListener("closeRelationDialog", function(evt){
      const dialog = document.getElementById("relationdialog");
      dialog.close();
    })

        </script>
        {% block scripts %}
        {% endblock %}
        {% block scripts2 %}
        {% endblock scripts2 %}
    </div>
</body>
</html>

mine_frontend/templates/mine_frontend/date_slider.html
{% load static %}
<div class="date-slider-wrapper">
    <div id="slider-{{ slider_name }}"
         class="mine-date-slider"
         data-min="1847"
         data-max="2025"
         data-form-lower="start_date_form"
         data-form-upper="end_date_form"></div>
    <legend id="slider-mitgld-description" class="legend-date-slider">
        Alle Mitgliedschaften die während der ausgewählten Periode aufrecht waren werden angezeigt.
        <br />
        <span id="lower-bound">Mitgliedschaften <b>können vor</b> <span id="lower-year">1847</span> beginnen und <b>müssen nach</b> <span id="lower-year">1847</span> enden.</span>&nbsp;<span id="upper-bound">Mitgliedschaften müssen vor <span id="upper-year">2025</span> starten und <b>können nach</b> <span id="upper-year">2025</span> enden.</span>
        <br />
        Mit einem <b>Doppelclick</b> auf die eingestellten Zeitrahmen zwischen durchlässigen (blau) und ausschliessenden (rot) umschalten.
    </legend>
    <template id="slider-lower-selected">
        Mitgliedschaften <b>müssen</b> <span id="lower-year"></span> oder danach beginnen.
    </template>
    <template id="slider-lower-not-selected">
        Mitgliedschaften <b>können vor</b> <span id="lower-year"></span> beginnen und <b>müssen nach</b> <span id="lower-year"></span> enden.
    </template>
    <template id="slider-upper-selected">
        Mitgliedschaften <b>müssen</b> <span id="upper-year"></span> oder davor enden.
    </template>
    <template id="slider-upper-not-selected">
        Mitgliedschaften müssen vor <span id="upper-year"></span> starten und <b>können nach</b> <span id="upper-year"></span> enden.
    </template>
</div>

mine_frontend/templates/mine_frontend/index.html
{% extends "mine_frontend/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block scriptHeader %}
    {{ block.super }}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/1.1.2/js/bootstrap-multiselect.min.js"></script>
    <script src="{% static 'js/apis_select2.js' %}"></script>
    <script src="{% static 'autocomplete_light/autocomplete_light.js' %}"></script>
    <script src="{% static 'nouislider/nouislider.min.js' %}"></script>
    <script src="{% static 'wnumb/wNumb.min.js' %}"></script>
    <script src="{% static 'mine_frontend/js/date_slider.js' %}"></script>
{% endblock scriptHeader %}
{% block content %}
    <div class="wrapper" id="wrapper-hero">
        <!-- ******************* The Hero Area ******************* -->
        <div class="wrapper  pb-0" id="wrapper-hero-content">
            <div class="container pl-5 pr-5 hero-light"
                 id="wrapper-hero-inner"
                 tabindex="-1">
                <div class="row m-0 bg-mine border-mine p-1">
                    <h1 class="w-50  font-weight-bold">Mitglieder der Österreichischen Akademie der Wissenschaften</h1>
                    <div class="w-75 mx-auto">
                        <p class="font-weight-normal">
                            Die Österreichische Akademie der Wissenschaften besteht aus zwei Klassen,
                            der mathematisch-naturwissenschaftlichen und der philosophisch-historischen
                            Klasse. Die Gelehrtengesellschaft ergänzt sich selbst durch die Wahl neuer Mitglieder.
                        </p>
                    </div>
                </div>
            </div>
            <!-- #wrapper-hero-content -->
        </div>
        <div class="wrapper pt-0" id="index-wrapper">
            <div class="container pl-5 pr-5" id="content" tabindex="-1">
                {% block search-form %}
                    <form action="/search?" class="w-100" method="get">
                        <div id="search_form">{% crispy search_form search_form.helper %}</div>
                    </form>
                {% endblock search-form %}
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    {{ block.super }}
    <script>document.addEventListener('DOMContentLoaded', startDateSliders)</script>
{% endblock scripts %}